// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsNcIylBXTKKsW7iByeLOyylGIAbWU38Q',
    appId: '1:778615648424:web:ddf17cfd829c44c1f3529d',
    messagingSenderId: '778615648424',
    projectId: 'tashop-e828b',
    authDomain: 'tashop-e828b.firebaseapp.com',
    storageBucket: 'tashop-e828b.appspot.com',
    measurementId: 'G-WEFP1DCKXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3VUAnmtMkqhNMKLmynCb1M1z7tFhtJA',
    appId: '1:778615648424:android:1769eb2df8e698e1f3529d',
    messagingSenderId: '778615648424',
    projectId: 'tashop-e828b',
    storageBucket: 'tashop-e828b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDnMMglTYy0EYoPTdNeCUUdWcDqG2fQIc',
    appId: '1:778615648424:ios:552f937e2981f6f1f3529d',
    messagingSenderId: '778615648424',
    projectId: 'tashop-e828b',
    storageBucket: 'tashop-e828b.appspot.com',
    iosBundleId: 'com.example.taShop',
  );
}
